// i18n.js
import i18n from 'i18next';
import {initReactI18next} from 'react-i18next';

const resources = {
  english: {
    translation: {
      chooseLanguage: 'Choose language',
      selectLanguage: 'Select Language',
      english: 'English',
      marathi: 'Marathi',
      hindi: 'Hindi',
      continue: 'Continue',
      close: 'Close',
      'Get Started': 'Get Started',
      Welcome: 'Welcome',
      'Choose your role to access': 'Choose your role to access',
      'Treatment Center': 'Treatment Center',
      Rescuer: 'Rescuer',
      Guest: 'Guest',
      'Sign In': 'Sign In',
      'Log In': 'Log In',
      'Sign Up': 'Sign Up',
      'Center Name': 'Center Name',
      'Center Location': 'Center Location',
      'Email ID (optional)': 'Email ID (optional)',
      'Contact Number': 'Contact Number',
      Next: 'Next',
      'Authorizes Signature': 'Authorizes Signature',
      Description: 'Description',
      'Patient Form': 'Patient Form',
      'Patient Details': 'Patient Details',
      Name: 'Name',
      Age: 'Age',
      'Contact details of patient': 'Contact details of patient',
      address: 'address',
      'Snakebite Details': 'Snakebite Details',
      'Snake ID(if available)': 'Snake ID(if available)',
      'bite location(area)': 'bite location(area)',
      'affected body part': 'affected body part',
      'used ASV on the patient': 'used ASV on the patient',
      'rescuer name': 'rescuer name',
      'Snakebite Details': 'Snakebite Details',
      Save: 'Save',
      'Profile Tab': 'Profile Tab',
      'Profile update': 'Profile update',
      'Stock availability of ASV': 'Stock availability of ASV',
      'patient list': 'patient list',
      'Add new patient': 'Add new patient',
      'Patient List': 'Patient List',
      'Snake ID': 'Snake ID',
      'Number of ASV': 'Number of ASV',
      'Patient Profile': 'Patient Profile',
      Gender: 'Gender',
      'Discharge Details': 'Discharge Details',
      'Patient Status': 'Patient Status',
      'Any Disability Caused': 'Any Disability Caused',
      Username: 'Username',
      Password: 'Password',
      'Authorizes name': 'Authorizes name',
      'COPYRIGHT © 2024 WFN, ALL RIGHTS RESERVED':'COPYRIGHT © 2024 WFN, ALL RIGHTS RESERVED',
      'Developed by KodSoft':'Developed by KodSoft'

    },
  },
  marathi: {
    translation: {
      chooseLanguage: 'भाषा निवडा',
      selectLanguage: 'भाषा निवडा',
      english: 'इंग्रजी',
      marathi: 'मराठी',
      hindi: 'हिंदी',
      continue: 'सुरू ठेवा',
      close: 'बंद',
      'Get Started': 'प्रारंभ करा',
      Welcome: 'स्वागत आहे',
      'Choose your role to access': 'प्रवेश करण्यासाठी तुमची भूमिका निवडा',
      'Treatment Center': 'उपचार केंद्र',
      Rescuer: 'बचाव करणारा',
      Guest: 'अतिथी ',
      'Sign In': 'साइन इन करा',
      'Log In': 'लॉग इन करा',
      'Sign Up': 'नोंद करा',
      'Center Name': 'केंद्राचे नाव',
      'Center Location': 'केंद्र स्थान',
      'Email ID (optional)': 'ईमेल आयडी (पर्यायी)',
      'Contact Number': 'संपर्क क्रमांक',
      Next: 'पुढे',
      'Authorizes Signature': 'अधिकृत स्वाक्षरी करा',
      Description: 'वर्णन',
      'Patient Form': 'रुग्ण फॉर्म',
      'Patient Details': 'रुग्णाचे तपशील',
      Name: 'नाव',
      Age: 'वय',
      'Contact details of patient': 'रुग्णाचा संपर्क तपशील',
      address: 'पत्ता',
      'Snakebite Details': 'सर्पदंश तपशील',
      'Snake ID(if available)': 'साप आयडी (उपलब्ध असल्यास)',
      'bite location(area)': 'चाव्याचे स्थान (क्षेत्र)',
      'affected body part': 'प्रभावित शरीराचा भाग',
      'used ASV': 'रुग्णावर वापरलेले ASV',
      'Rescuer name': 'बचावकर्त्याचे नाव',
      'Snakebite Details': 'सर्पदंश तपशील',
      Save: 'जतन करा',
      'Profile Tab': 'प्रोफाइल टॅब',
      'Profile update': 'प्रोफाइल अपडेट',
      'Stock availability of ASV': 'ASV च्या स्टॉकची उपलब्धता',
      'patient list': 'रुग्णांची यादी',
      'Add new patient': 'नवीन रुग्ण जोडा',
      'Patient List': 'रुग्णांची यादी',
      'Snake ID': 'साप ID',
      'Number of ASV': 'ASV ची संख्या',
      'Patient Profile': 'रुग्ण प्रोफाइल',
      Gender: 'लिंग',
      'Discharge Details': 'डिस्चार्ज तपशील',
      'Patient Status': 'रुग्णाची स्थिती',
      'Any Disability Caused': 'कोणत्याही अपंगत्वामुळे',
      Username: 'वापरकर्ता नाव',
      Password: 'पासवर्ड',
      'Authorizes name': 'नाव अधिकृत करते',
      'COPYRIGHT © 2024 WFN, ALL RIGHTS RESERVED':'कॉपीराइट © 2024 WFN, सर्व हक्क राखीव',
      'Developed by KodSoft':'KodSoft द्वारे विकसित',
      'Forgot Password?':'पासवर्ड विसरलात?',
      'New here? Create an account':'येथे नवीन? खाते तयार करा',
      'Please Enter Your Email address To Receive a Verification Code':'सत्यापन कोड प्राप्त करण्यासाठी कृपया आपला ईमेल पत्ता प्रविष्ट करा',
      "Enter Your Email Address.":"तुमचा ईमेल पत्ता प्रविष्ट करा.",
      'Try Another Way ?':'दुसरा मार्ग वापरून पहा?',
      'Send':'पाठवा',
      'Verify Your Mobile No.':'तुमचा मोबाईल नंबर सत्यापित करा.',
      'Please Enter The 4 Digit Code Sent To 9********7':'कृपया 9*******7 वर पाठवलेला 4 अंकी कोड प्रविष्ट करा',
      'Resend Code':'कोड पुन्हा पाठवा',
      'Verify':'सत्यापित करा',
      'Create New Password':'नवीन पासवर्ड तयार करा',
      'Enter New Password':'नवीन पासवर्ड टाका',
      'Confirm Password':'पासवर्डची पुष्टी करा',
      'Change Password':'पासवर्ड बदला',
      "Centre name":"केंद्राचे नाव",
      "Centre location":"केंद्र स्थान",
      "Email ID (Optional)":"ईमेल आयडी (पर्यायी)",
      "Email ID":"ईमेल आयडी",
      "Contact number":"संपर्क क्रमांक",
      "Authorizes Name":"नाव अधिकृत करते",
      "Availability of ASV":"ASV ची उपलब्धता",   
      "Current stock ASV":"वर्तमान स्टॉक ASV",   
      "Description":"वर्णन",
      "Password":"पासवर्ड",
      "Confirm Password":"पासवर्डची पुष्टी करा",
      "Location/Address":"स्थान/पत्ता",
      "Years Of Experience":"वर्षांचा अनुभव",
      "Education":"शिक्षण",
      "Enter your Password":"तुमचा पासवर्ड प्रविष्ट करा",
      "Confirm your Password":"तुमच्या पासवर्डची पुष्टी करा",
      "Gov ID":'सरकारी आयडी',
      "Address":"पत्ता",
      "expertise/profession":"विशेषज्ञता/व्यवसाय",
      'Send Admin Request for Activation':"सक्रियतेसाठी प्रशासन विनंती पाठवा",
      'Request':'विनंती',
      'Save and Exit':'जतन करा आणि बाहेर पडा',
      'Upload photo':'फोटो अपलोड करा',
      'Submit':'सबमिट करा',
      'Experience':'अनुभव',
      'User':'वापरकर्ता',
      'Expertise/Profession':'कौशल्य/व्यवसाय',
      'Substract':'वजा करा',
      'Add':'अधिक',
      'Stock of ASV':'ASV चा साठा',
      'Home':'होम',
      'Explore':'एक्स्प्लोर',
      'Profile':'प्रोफाइल',
      'Edit Profile':'प्रोफाइल संपादित करा',
      'Setting':'सेटिंग',
      'About Us':'अबाउट us',
      'Privacy Policy':'प्राइवेसी पालिसी',
      'Logout':'लॉगआउट',
      'Last stocked on':'शेवटचे स्टॉक केलेले',
      'Stock ASV':'स्टॉक ASV',
      'Last used on':'शेवटचा वापर',
      'Anti Snake Venom':'अँटी स्नेक व्हेनम',
      'Rescue Details':'बचाव तपशील',
      'Upload Rescue':'अपलोड रेस्क्यू',
      'Rescued Animals':'रेस्क्यु केलेले प्राणी',
      'Select Action':'कृती निवडा',
      'Edit ASV':'ASV संपादित करा',
      'Cancel':'रद्द करा',
      'Nearby Treatment Centre':'जवळील उपचार केंद्र',
      'Rescuer list':'बचावकर्त्यांची सूची',
      'List':'सूची',
      'Upload Post':'पोस्ट अपलोड',
      'Posts':'पोस्ट',
      'Update':'अपडेट',
      'Current Location':'सध्याचे स्थान',
      'Manual Location':'मैन्युअल स्थान',
      'Upload':'अपलोड',
      'Recent Posts':'अलीकडील पोस्ट',
      'Search by username':'वापरकर्ता नावाने शोधा'
    },
  },
  hindi: {
    translation: {
      chooseLanguage: 'भाषा चुनें',
      selectLanguage: 'भाषा चुनें',
      english: 'अंग्रेजी',
      marathi: 'मराठी',
      hindi: 'हिंदी',
      continue: 'जारी रखें',
      close: 'बंद करें',
      'Get Started': 'शुरू हो जाओ',
      Welcome: 'स्वागत है',
      'Choose your role to access': 'एक्सेस करने के लिए अपनी भूमिका चुनें',
      'Treatment Center': 'उपचार केंद्र',
      Rescuer: 'बचानेवाला',
      Guest: 'अतिथी ',
      'Sign In': 'दाखिल करे',
      'Log In': 'लॉग इन करें',
      'Sign Up': 'नामंकित करे',
      'Center Name': 'केंद्र का नाम',
      'Center Location': 'केंद्र स्थान',
      'Email ID (optional)': 'ईमेल आईडी (वैकल्पिक)',
      'Contact Number': 'संपर्क क्रमांक',
      'Authorizes name': 'अधिकृत नाम',
      Next: 'अगला',
      'Authorizes Signature kare ': 'अधिकृत हस्ताक्षर करे',
      Description: 'विवरण',
      'Patient Form': 'रोगी प्रपत्र',
      'Patient Details': 'रोगी विवरण',
      Name: 'नाम',
      Age: 'आयु',
      'Contact details of patient': 'रोगी का संपर्क विवरण',
      address: 'पता',
      'Snakebite Details': 'सर्पदंश विवरण',
      'Snake ID(if available)': 'साँप आईडी (यदि उपलब्ध हो)',
      'bite location(area)': 'काटने का स्थान (क्षेत्र)',
      'affected body part': 'शरीर का प्रभावित भाग',
      'used ASV': 'मरीज पर प्रयोग किया ASV',
      'Rescuer name': 'बचाने वाले का नाम',
      'Snakebite Details': ' सर्पदंश विवरण',
      Save: 'जतन करे',
      'Profile Tab': 'प्रोफ़ाइल टैब',
      'Profile update': 'प्रोफ़ाइल अद्यतन',
      'Stock availability of ASV': 'ASV की स्टॉक उपलब्धता',
      'patient list': 'रोगी सूची',
      'Add new patient': 'नये मरीज जोड़ें',
      'Patient List': 'रोगी सूची',
      'Snake ID': 'साँप की ID',
      'Number of ASV': 'ASV की संख्या',
      'Patient Profile': 'रोगी प्रोफ़ाइल',
      Gender: 'लिंग',
      'Discharge Details': 'निर्वहन विवरण',
      'Patient Status': 'रोगी की स्थिति',
      'Any Disability Caused': 'किसी भी प्रकार की विकलांगता के कारण',
      Username: 'उपयोगकर्ता नाम',
      Password: 'पासवर्ड',
      'COPYRIGHT © 2024 WFN, ALL RIGHTS RESERVED':'कॉपीराइट © 2024 WFN, सर्वाधिकार सुरक्षित',
         'Developed by KodSoft':'KodSoft द्वारा विकसित',
         'Forgot Password?':'पासवर्ड भूल गए?',
         'New here? Create an account':'अब यहां? खाता बनाएं',
         'Please Enter Your Email address To Receive a Verification Code':'सत्यापन कोड प्राप्त करने के लिए कृपया अपना ईमेल पता दर्ज करें',
         "Enter Your Email Address.":"अपना ईमेल पता दर्ज करें।",
         'Try Another Way ?':'कोई दूसरा तरीका आज़माएं?',
         'Send':'भेजो',
         'Verify Your Mobile No.':'अपना मोबाइल नंबर सत्यापित करें',
         'Please Enter The 4 Digit Code Sent To 9********7':'कृपया 9********7 पर भेजा गया 4 अंकीय कोड दर्ज करें',
         'Resend Code':'पुन: कोड भेजे',
         'Verify':'सत्यापित करें',
         'Create New Password':'नया पासवर्ड बनाएं',
         'Enter New Password':'नया पासवर्ड दर्ज करें',
         'Confirm Password':'पासवर्ड की पुष्टि कीजिये',
         'Change Password':'पासवर्ड बदलें',
         "Centre name":"केंद्र का नाम",
         "Centre location":"केंद्र स्थान",
         "Email ID (Optional)":"ईमेल आईडी (वैकल्पिक)",
         "Contact number":"संपर्क संख्या",
         "Authorizes Name":"प्राधिकृत नाम",
         "Availability of ASV":"ASV की उपलब्धता",
         "Current stock ASV":"वर्तमान स्टॉक ASV",
         "Description":"विवरण",
         "Password":"पासवर्ड",
         "Confirm Password":"पासवर्ड की पुष्टि कीजिये",
         "Location/Address":"स्थान का पता",
         "Years Of Experience":"वर्षों का अनुभव",
         "Education":"शिक्षा",
         "Enter your Password":"अपना कूटशब्द भरें",
         "Confirm your Password":"अपने पासवर्ड की पुष्टि करें",
         "Gov ID":'सरकारी आईडी',
         "Address":"पत्ता",
         "expertise/profession":"विशेषज्ञता/पेशा",
         'Send Admin Request for Activation':'सक्रियण के लिए व्यवस्थापक अनुरोध भेजें',
         'Request':'अनुरोध',
         'Save and Exit':'सहेजें और बाहर निकलें',
         'Upload photo':'फोटो अपलोड करें',
         'Submit':'जमा करे',
         'Experience':'अनुभव',
         'User':'उपयोगकर्ता',
         'Expertise/Profession':'विशेषज्ञता/पेशा',
         'Substract':'घटाएँ',
         'Add':'अतिरिक्त',
         'Stock of ASV':'ASV का स्टॉक',
         'Home':'होम',
         'Explore':'एक्स्प्लोर',
         'Profile':'प्रोफाइल',
         'Edit Profile':'प्रोफाइल संपादित करा',
         'Setting':'सेटिंग',
         'About Us':'अबाउट us',
         'Privacy Policy':'प्राइवेसी पालिसी',
         'Logout':'लॉगआउट',
         'Last stocked on':'आखिरी बार स्टॉक किया गया',
         'Stock ASV':'स्टॉक एएसवी',
         'Last used on':'आखिरी बार इस्तेमाल किया गया',
         'Anti Snake Venom':'एंटी स्नेक वेनम',
         'Rescue Details':'बचाव विवरण',
         'Upload Rescue':'अपलोड बचाव',
         'Rescued Animals':'बचाए गए जानवर',
         'Select Action':'कार्रवाई चुनें',
         'Edit ASV':'एएसवी संपादित करें',
         'Cancel':'रद्द करें',
         'Nearby Treatment Centre':'नजदीकी उपचार केंद्र',
         'Rescuer list':'बचावकर्ताओं की सूची',
         'List':'सूची',
         'Upload Post':'पोस्ट अपलोड',
         'Posts':'पोस्ट',
         'Update':'अपडेट',
         'Current Location':'वर्तमान स्थान',
         'Manual Location':'मैन्युअल स्थान',
         'Upload':'अपलोड',
         'Recent Posts':'हाल के पोस्ट',
         'Search by username':'उपयोगकर्ता नाम से खोजें'
    },
  },
};

i18n.use(initReactI18next).init({
  resources,
  lng: 'english',
  fallbackLng: 'english',
  interpolation: {
    escapeValue: false,
  },
});

export default i18n;


