// i18n.js
import i18n from 'i18next';
import {initReactI18next} from 'react-i18next';

const resources = {
  english: {
    translation: {
      chooseLanguage: 'Choose language',
      selectLanguage: 'Select Language',
      english: 'English',
      marathi: 'Marathi',
      hindi: 'Hindi',
      continue: 'Continue',
      close: 'Close',
      'Get Started': 'Get Started',
      Welcome: 'Welcome',
      'Choose your role to access': 'Choose your role to access',
      'Treatment Center': 'Treatment Center',
      Rescuer: 'Rescuer',
      Guest: 'Guest',
      'Sign In': 'Sign In',
      'Log In': 'Log In',
      'Sign Up': 'Sign Up',
      'Center Name': 'Center Name',
      'Center Location': 'Center Location',
      'Email ID (optional)': 'Email ID (optional)',
      'Contact Number': 'Contact Number',
      Next: 'Next',
      'Authorizes Signature': 'Authorizes Signature',
      Description: 'Description',
      'Patient Form': 'Patient Form',
      'Patient Details': 'Patient Details',
      Name: 'Name',
      Age: 'Age',
      'Contact details of patient': 'Contact details of patient',
      address: 'address',
      'Snakebite Details': 'Snakebite Details',
      'Snake ID(if available)': 'Snake ID(if available)',
      'bite location(area)': 'bite location(area)',
      'affected body part': 'affected body part',
      'used ASV on the patient': 'used ASV on the patient',
      'rescuer name': 'rescuer name',
      'Snakebite Details': 'Snakebite Details',
      Save: 'Save',
      'Profile Tab': 'Profile Tab',
      'Profile update': 'Profile update',
      'Stock availability of ASV': 'Stock availability of ASV',
      'patient list': 'patient list',
      'Add new patient': 'Add new patient',
      'Patient List': 'Patient List',
      'Snake ID': 'Snake ID',
      'Number of ASV': 'Number of ASV',
      'Patient Profile': 'Patient Profile',
      Gender: 'Gender',
      'Discharge Details': 'Discharge Details',
      'Patient Status': 'Patient Status',
      'Any Disability Caused': 'Any Disability Caused',
      Username: 'Username',
      Password: 'Password',
      'Authorizes name': 'Authorizes name',
    },
  },
  marathi: {
    translation: {
      chooseLanguage: 'भाषा निवडा',
      selectLanguage: 'भाषा निवडा',
      english: 'इंग्रजी',
      marathi: 'मराठी',
      hindi: 'हिंदी',
      continue: 'सुरू ठेवा',
      close: 'बंद',
      'Get Started': 'प्रारंभ करा',
      Welcome: 'स्वागत आहे',
      'Choose your role to access': 'प्रवेश करण्यासाठी तुमची भूमिका निवडा',
      'Treatment Center': 'उपचार केंद्र',
      Rescuer: 'बचाव करणारा',
      Guest: 'अतिथी ',
      'Sign In': 'साइन इन करा',
      'Log In': 'लॉग इन करा',
      'Sign Up': 'नोंद करा',
      'Center Name': 'केंद्राचे नाव',
      'Center Location': 'केंद्र स्थान',
      'Email ID (optional)': 'ईमेल आयडी (पर्यायी)',
      'Contact Number': 'संपर्क क्रमांक',
      Next: 'पुढे',
      'Authorizes Signature': 'अधिकृत स्वाक्षरी करा',
      Description: 'वर्णन',
      'Patient Form': 'रुग्ण फॉर्म',
      'Patient Details': 'रुग्णाचे तपशील',
      Name: 'नाव',
      Age: 'वय',
      'Contact details of patient': 'रुग्णाचा संपर्क तपशील',
      address: 'पत्ता',
      'Snakebite Details': 'सर्पदंश तपशील',
      'Snake ID(if available)': 'साप आयडी (उपलब्ध असल्यास)',
      'bite location(area)': 'चाव्याचे स्थान (क्षेत्र)',
      'affected body part': 'प्रभावित शरीराचा भाग',
      'used ASV on the patient': 'रुग्णावर ASV वापरले',
      'rescuer name': 'बचावकर्त्याचे नाव',
      'Snakebite Details': 'सर्पदंश तपशील',
      Save: 'जतन करा',
      'Profile Tab': 'प्रोफाइल टॅब',
      'Profile update': 'प्रोफाइल अपडेट',
      'Stock availability of ASV': 'ASV च्या स्टॉकची उपलब्धता',
      'patient list': 'रुग्णांची यादी',
      'Add new patient': 'नवीन रुग्ण जोडा',
      'Patient List': 'रुग्णांची यादी',
      'Snake ID': 'साप ID',
      'Number of ASV': 'ASV ची संख्या',
      'Patient Profile': 'रुग्ण प्रोफाइल',
      Gender: 'लिंग',
      'Discharge Details': 'डिस्चार्ज तपशील',
      'Patient Status': 'रुग्णाची स्थिती',
      'Any Disability Caused': 'कोणत्याही अपंगत्वामुळे',
      Username: 'वापरकर्ता नाव',
      Password: 'पासवर्ड',
      'Authorizes name': 'नाव अधिकृत करते',
    },
  },
  hindi: {
    translation: {
      chooseLanguage: 'भाषा चुनें',
      selectLanguage: 'भाषा चुनें',
      english: 'अंग्रेजी',
      marathi: 'मराठी',
      hindi: 'हिंदी',
      continue: 'जारी रखें',
      close: 'बंद करें',
      'Get Started': 'शुरू हो जाओ',
      Welcome: 'स्वागत है',
      'Choose your role to access': 'एक्सेस करने के लिए अपनी भूमिका चुनें',
      'Treatment Center': 'उपचार केंद्र',
      Rescuer: 'बचानेवाला',
      Guest: 'अतिथी ',
      'Sign In': 'दाखिल करे',
      'Log In': 'लॉग इन करें',
      'Sign Up': 'नामंकित करे',
      'Center Name': 'केंद्र का नाम',
      'Center Location': 'केंद्र स्थान',
      'Email ID (optional)': 'ईमेल आईडी (वैकल्पिक)',
      'Contact Number': 'संपर्क क्रमांक',
      'Authorizes name': 'अधिकृत नाम',
      Next: 'अगला',
      'Authorizes Signature kare ': 'अधिकृत हस्ताक्षर करे',
      Description: 'विवरण',
      'Patient Form': 'रोगी प्रपत्र',
      'Patient Details': 'रोगी विवरण',
      Name: 'नाम',
      Age: 'आयु',
      'Contact details of patient': 'रोगी का संपर्क विवरण',
      address: 'पता',
      'Snakebite Details': 'सर्पदंश विवरण',
      'Snake ID(if available)': 'साँप आईडी (यदि उपलब्ध हो)',
      'bite location(area)': 'काटने का स्थान (क्षेत्र)',
      'affected body part': 'शरीर का प्रभावित भाग',
      'used ASV on the patient': 'मरीज पर ASV का प्रयोग किया',
      'rescuer name': 'बचाने वाले का नाम',
      'Snakebite Details': ' सर्पदंश विवरण',
      Save: 'जतन करे',
      'Profile Tab': 'प्रोफ़ाइल टैब',
      'Profile update': 'प्रोफ़ाइल अद्यतन',
      'Stock availability of ASV': 'ASV की स्टॉक उपलब्धता',
      'patient list': 'रोगी सूची',
      'Add new patient': 'नये मरीज जोड़ें',
      'Patient List': 'रोगी सूची',
      'Snake ID': 'साँप की ID',
      'Number of ASV': 'ASV की संख्या',
      'Patient Profile': 'रोगी प्रोफ़ाइल',
      Gender: 'लिंग',
      'Discharge Details': 'निर्वहन विवरण',
      'Patient Status': 'रोगी की स्थिति',
      'Any Disability Caused': 'किसी भी प्रकार की विकलांगता के कारण',
      Username: 'उपयोगकर्ता नाम',
      Password: 'पासवर्ड',
    },
  },
};

i18n.use(initReactI18next).init({
  resources,
  lng: 'english',
  fallbackLng: 'english',
  interpolation: {
    escapeValue: false,
  },
});

export default i18n;
